### PR TITLE
task-6

### PR DESCRIPTION
**Pull request by gerrkoff**
[Application](https://d2m0zjd9gr3n46.cloudfront.net/)
[CSV file example](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/products.csv)

# Tasks (+70)
- [x] AWS CDK Stack contains configuration for `catalogBatchProcess` function
[`catalogBatchProcessorFunction` in AWS CDK Stack](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/deployment/Deployment/ProductServiceStack.cs#L88)

- [x] AWS CDK Stack contains policies to allow lambda `catalogBatchProcess` function to interact with SNS and SQS
[`catalogBatchProcessorFunction.AddEventSource`](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/deployment/Deployment/ProductServiceStack.cs#L113)
[`snsTopic.GrantPublish`](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/deployment/Deployment/ProductServiceStack.cs#L118)

- [x] AWS CDK Stack contains configuration for SQS `catalogItemsQueue`
[`CatalogItemsQueue`](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/deployment/Deployment/ProductServiceStack.cs#L107)

- [x] AWS CDK Stack contains configuration for SNS Topic `createProductTopic` and email subscription
[`snsTopic`](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/deployment/Deployment/ProductServiceStack.cs#L25)
[Email subscription](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/deployment/Deployment/ProductServiceStack.cs#L29)

# Additional Scope (+30)
- [x] `catalogBatchProcess` lambda is covered by unit tests
[CatalogBatchProcessorTest.cs](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/product-service/ProductService.Tests/CatalogBatchProcessorTest.cs#L11)

- [x] set a Filter Policy for SNS `createProductTopic` in AWS CDK Stack and create an additional email subscription to distribute messages to different emails depending on the filter for any product attribute
[Additional subscription with Filter Policy](https://github.com/gerrkoff/rs-aws-cloud-developer/blob/task-6c/deployment/Deployment/ProductServiceStack.cs#L30)

Notification about `Super expensive product` was delivered to both `me` and `ragnareck` recipients.
image

### CODE REVIEW

**Comment by furiousme** [comment]
@gerrkoff 
Hello! I tried to upload two different files with products but the items didn't appear in the list after that. Could you please check the logs to figure out what happened?

**Comment by gerrkoff** [comment]
> @gerrkoff Hello! I tried to upload two different files with products but the items didn't appear in the list after that. Could you please check the logs to figure out what happened?

@furiousme Hi! Here are the logs:
```
2024-07-08T12:43:58.091Z	40a8de37-124f-4d62-a2ce-659e41327c0c	fail	Error parsing file: uploaded/beauty_care_products.csv, exception: Header with name 'Id'[0] was not found.
Header with name 'Title'[0] was not found.
Header with name 'Description'[0] was not found.
Header with name 'Price'[0] was not found.
Header with name 'Count'[0] was not found.
Headers: 'title', 'description', 'price', 'count'
If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.

IReader state:
   ColumnCount: 4
   CurrentIndex: -1
   HeaderRecord:
["title","description","price","count"]
IParser state:
   ByteCount: 0
   CharCount: 30
   Row: 1
   RawRow: 1
   Count: 4
   RawRecord:
title,description,price,count
```
As far as I understand, you're trying to pass `title,description,price,count` headers, whereas my parser is expecting `Id,Title,Description,Price,Count` (with `Id` also included).

I've adjusted PR description and added there a link with an example of `products.csv` file that should work fine. Would you mind trying to either change your file or use mine as an example?

**Comment by furiousme** [comment]
@gerrkoff sure, I'll do. Thanks!

**Comment by furiousme** [comment]
> > @gerrkoff Hello! I tried to upload two different files with products but the items didn't appear in the list after that. Could you please check the logs to figure out what happened?
> 
> @furiousme Hi! Here are the logs:
> 
> ```
> 2024-07-08T12:43:58.091Z	40a8de37-124f-4d62-a2ce-659e41327c0c	fail	Error parsing file: uploaded/beauty_care_products.csv, exception: Header with name 'Id'[0] was not found.
> Header with name 'Title'[0] was not found.
> Header with name 'Description'[0] was not found.
> Header with name 'Price'[0] was not found.
> Header with name 'Count'[0] was not found.
> Headers: 'title', 'description', 'price', 'count'
> If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.
> 
> IReader state:
>    ColumnCount: 4
>    CurrentIndex: -1
>    HeaderRecord:
> ["title","description","price","count"]
> IParser state:
>    ByteCount: 0
>    CharCount: 30
>    Row: 1
>    RawRow: 1
>    Count: 4
>    RawRecord:
> title,description,price,count
> ```
> 
> As far as I understand, you're trying to pass `title,description,price,count` headers, whereas my parser is expecting `Id,Title,Description,Price,Count` (with `Id` also included).
> 
> I've adjusted PR description and added there a link with an example of `products.csv` file that should work fine. Would you mind trying to either change your file or use mine as an example?



> > @gerrkoff Hello! I tried to upload two different files with products but the items didn't appear in the list after that. Could you please check the logs to figure out what happened?
> 
> @furiousme Hi! Here are the logs:
> 
> ```
> 2024-07-08T12:43:58.091Z	40a8de37-124f-4d62-a2ce-659e41327c0c	fail	Error parsing file: uploaded/beauty_care_products.csv, exception: Header with name 'Id'[0] was not found.
> Header with name 'Title'[0] was not found.
> Header with name 'Description'[0] was not found.
> Header with name 'Price'[0] was not found.
> Header with name 'Count'[0] was not found.
> Headers: 'title', 'description', 'price', 'count'
> If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.
> 
> IReader state:
>    ColumnCount: 4
>    CurrentIndex: -1
>    HeaderRecord:
> ["title","description","price","count"]
> IParser state:
>    ByteCount: 0
>    CharCount: 30
>    Row: 1
>    RawRow: 1
>    Count: 4
>    RawRecord:
> title,description,price,count
> ```
> 
> As far as I understand, you're trying to pass `title,description,price,count` headers, whereas my parser is expecting `Id,Title,Description,Price,Count` (with `Id` also included).
> 
> I've adjusted PR description and added there a link with an example of `products.csv` file that should work fine. Would you mind trying to either change your file or use mine as an example?

Ok, so I've tried with the file you provided as well as the same one but the first product data changed (another Id, title, and description). Both didn't work. Quite strange.

**Comment by gerrkoff** [comment]
@furiousme what is the content of the file you're trying to sent? In logs I see the same `Product 1` added three times

```
2024-07-08T13:09:09.027Z	a7df4c87-9686-4d82-90c3-ead23b38141e	info	Found in File: uploaded/products.csv Product: 
{
    "id": "3525348c-9277-4ae5-ba8e-9da1cccfdd4e",
    "title": "product 1",
    "description": "description 1",
    "price": 100,
    "count": 10
}
```
```
2024-07-08T13:10:24.486Z	abe2e4b6-36e4-4489-813e-71f9d6f1c759	info	Found in File: uploaded/products.csv Product: 
{
    "id": "3525348c-9277-4ae5-ba8e-9da1cccfdd4e",
    "title": "product 1",
    "description": "description 1",
    "price": 100,
    "count": 10
}
```
```
2024-07-08T13:16:50.901Z	9752d34f-cae1-49b5-935c-c17fd3e1f4e6	info	Found in File: uploaded/products.csv Product: 
{
    "id": "3525348c-9277-4ae5-ba8e-9da1cccfdd4e",
    "title": "product 1",
    "description": "description 1",
    "price": 100,
    "count": 10
}
```
Since Id is the same, item is not added, but updated.

**Comment by furiousme** [comment]
@gerrkoff 
Just in case you want to continue debugging here is the content of the file. Anyway, there are no requirements for reviewers to check the uploading functionality so I'm not going to cut off the points :)

```
Id,Title,Description,Price,Count
3c512f81-55aa-4308-8054-5d8e51fd981c,New product 1,New description 1,100,10
2aaba5a2-0072-4268-ae2d-24db59566dd7,product 2,description 2,200,20
318454b6-0d24-4e36-889b-f0df1c4e7fa6,product 3,description 3,300,30
f9e9b1b7-b34f-4eb5-98df-5380168c3a31,product 4,description 4,400,40
60057269-4871-4375-8653-f076d1d2c9d9,product 5,description 5,500,50
60057269-4871-4375-8653-f076d1d2c9d0,super expensive product,super expensive description,100500,100
```

**Comment by gerrkoff** [comment]
@furiousme that's weird. I put your content into this `test.csv` file and it worked for me (with some delay as expected). 
[test.csv](https://github.com/user-attachments/files/16130631/test.csv)

Anyway, thanks for being so patient :)

**Pull request merged**
